### ISSUE TITLE
It would be nice if there was a way of vetoing the selection

### ISSUE THREAD

**Issue by rasto68** [PolymerElements/iron-selector#111]
We are using iron-selector in a simple accordion menu type control but occasionally we need to be able to cancel a selection, iron-selector doesn't currently support this (via the API I can see anyway) leading to some annoying logic at slightly higher level in the code.

**Comment by bicknellr** [comment]
Hi, @rasto68, you can listen for `iron-activate` events and cancel them to prevent the selection from occuring ([code](https://github.com/PolymerElements/iron-selector/blob/7597294/iron-selectable.html#L343), [docs](https://github.com/PolymerElements/iron-selector/blob/7597294/iron-selectable.html#L19)). [Here's a demo.](http://jsbin.com/xigayi/1/edit?html,output) Let me know if this isn't what you meant or is insufficient and I'll reopen; otherwise, thanks for filing!

**Comment by rasto68** [comment]
Thanks Russell that looks like it could help :)
