### ISSUE TITLE
Duplicate API: selectedAttribute and attributeForSelected

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-selector#32]
Do these two properties do the same thing?

`selectedAttribute`
https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L96

`attributeForSelected`
https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L27

Preferably, we should keep the first been around since the 0.5 days.

**Comment by notwaldorf** [comment]
I don't think they are the same thing. `Paper-radio-group` uses both:
- `selectedAttribute` is the attribute the menu is applying on the item when it's selected: https://github.com/PolymerElements/paper-radio-group/blob/master/paper-radio-group.html#L82
- `attrForSelected` is the item's attribute used to make a selection (for example `name` instead of `index`): https://github.com/PolymerElements/paper-radio-group/blob/master/paper-radio-group.html#L74

**Comment by ebidel** [comment]
Thanks for clarifying. I think some my confusion is because 0.5's `selectedAttribute` was `attrForSelected`'d semantics. That is IIRC, 0.5's `selectedAttribute` didn't add the attribute to the selected element, it just looked for that attr to make a selection. Closing
