### ISSUE TITLE
How do you clear the current selection so that no items are selected?

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/iron-selector#54]

**Comment by jodekirk** [comment]
I don't know if there's a clear() function, but setting the selectedItems and selectedValues to [] seems to work.
For example if you have an iron-selector with id="selector":
this code clears the selected items.
    this.$.selector.selectedItems=[];
    this.$.selector.selectedValues=[];

**Comment by jodekirk** [comment]
oops. I swear that code worked the first couple times I tried in the Chrome 64 Dev browser, but now I'm getting console errors: 
Uncaught TypeError: Cannot set property selectedItems of #<iron-selector> which has only a getter

**Comment by arthurevans** [comment]
See the doc here:

https://elements.polymer-project.org/elements/iron-selector?active=Polymer.IronMultiSelectableBehavior

`selectedItems` is read-only. `selectedValues` is read/write. Setting that should clear the selection.

Note that `selectedValues` doesn't _reflect_, so if you're looking at the element in the inspector, **and** `selectedValues` was set to a literal array in markup, you'll see the original value on the **attribute** (like, `selected-values="[1,3]"`) in the DOM tree. This isn't a problem and it doesn't affect data binding or anything else -- I just mention it because it's a potential source of confusion.

**Comment by cdata** [comment]
I believe that this issue has been resolved. Please re-open if it is still unclear how to clear the selected items!
